services:
  - type: web
    name: routeloop-gateway
    runtime: docker
    plan: free
    dockerfilePath: ./gateway/Dockerfile
    dockerContext: ./gateway
    healthCheckPath: /healthz
    envVars:
      - key: DEFAULT_PROVIDER
        value: gemini
      - key: WEB_ORIGIN
        sync: false
      - key: ROUTELOOP_API_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
  - type: web
    name: routeloop-evaluator
    runtime: docker
    plan: free
    dockerfilePath: ./evaluator/Dockerfile
    dockerContext: ./evaluator
    healthCheckPath: /healthz
    envVars:
      - key: WEB_ORIGIN
        value: https://routeloop-ten.vercel.app
      - key: EVALUATOR_API_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
