ALTER TABLE traces ADD COLUMN IF NOT EXISTS prompt_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS completion_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS total_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS http_status INTEGER NOT NULL DEFAULT 200;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS routing_reason TEXT NOT NULL DEFAULT 'default-provider';
CREATE INDEX IF NOT EXISTS traces_status_created_at_idx ON traces (status, created_at DESC);
